### ISSUE TITLE
Proposal peer review for Feature Finders Club

### ISSUE THREAD

**Issue by Rohit-Hemaraja** [INFO-523-Exercises/project-final-Feature-Finders-Club#28]
The following is the peer review of the project proposal by The Null Wranglers. The team members that participated in this review are 

- Dong Chen - @dongchen18
- Anjani Sowmya Bollapragada - @asbollapragada
- Kristi Manasil - @kmanasil
- Rohit Hemaraja- @Rohit-Hemaraja
- Utkarsha Patil- @utkarshapatil01

- Describe the goal of the project.

      Create a final model that will predict stock market prices for tech stocks based news sentiment analysis

- Describe the data used or collected.

  1) They are using an API call to retrieve the stock information. 
  2) Includes Datetime in the format of year - month - day. It includes opening, high and closing as well as volume, dividends and stock splits.
  3) Unsure of what data sets they will be using for the news sentiment analysis
  4) Unsure about how the “dividend” column is contributing towards the sentiment analysis.	

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

  1) They plan to do a descriptive analysis to identify patterns. They then plan to use possible patterns or trends to conduct a correlation analysis to identify features that may be well suited for predictive analysis.
  2) Create visualizations to demonstrate the findings of the descriptive and correlational analysis.

- Is there anything that is unclear from the proposal?

  1) We do not understand how analyzing just one stock within the tech sector will be an adequate representation of the “sectors”.
  2) They also mention other sectors in the introduction that are not explained further what sectors or what stocks.
  3) Unsure about what data they are looking for.
  4) Unsure about how they plan to analyze the news sentiment and there is no data for news headlines
  

- Provide constructive feedback on how the team might be able to improve their project.
  
  1) Include more information about the news data, what sentiments they will be classifying
  2) Include the timeframe of the stock and news data used in the analysis
  3) Consider including more than just Apple stock to represent the tech sector or change the project to focus on just Apple stock prices in relation to news sentiment.
  4)In your opening statement you identify that you plan to build a predictive model but only focus on correlation analysis and not what type of predictive model you are building and what exactly you are predicting

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
       
        The idea of sentiment analysis in connection to apple stock prices is interesting and can have an impact on day to day life. Using sentiment analysis to create a predictive model for stock prices would be beneficial to investors for future stock purchases.

- Provide constructive feedback on any issues with file and/or code organization.
    
     We found it well organized and have no recommendations to improve this

- (Optional) Any further comments or feedback?
  None

**Comment by eshaanmathakari** [comment]
Hi, thank you for your review! We have made the changes as per your feedback.
