### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by kendall-beaver** [INFO-523-Exercises/project-final-Feature-Finders-Club#29]
The following is the peer review of the project proposal by the Byte Busters. The team members that participated in this review are 

- Riyanshi - @riyanshibohra
- Dhanya - @SaiDhanyaa
- Ajinkya - @ajinkyapdeshmukh10
- Kendall - @kendallbeaver
- Udit - @uditChaudhary242

- Describe the goal of the project.

1. The goal is a bit difficult to understand because there's a lot of convoluted terminology.
2. A simple high-level goal at the beginning would have helped us understand this better.

- Describe the data used or collected.

1. There's no link for us to visit the source of the data for easy access.
2. It would be better if the data description was given in a table format. The data dictionary is not formatted for the .qmd format file type.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

1. The first question is not professionally written and does not explain the objective well, although it is evident in the Analysis Plan that they will be using data visualization methods and sentiment analysis.
2. The second question is written better than the first question and has a good motivation behind the question. They will be using data visualization methods.

- Is there anything that is unclear from the proposal?

1. From the first question we need to know what variables they will using for their predictive analysis.
2. The objective is very broad and is difficult to understand what exactly what is the main goal of the project. 

- Provide constructive feedback on how the team might be able to improve their project.

The project is very broad so narrowing down and making the project more focused will result in a more simple and better analysis.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

The data visualization with stock prices and news headlines will be interesting to analyze and see what insights will occur in affecting stock prices in the technology sector.

- Provide constructive feedback on any issues with file and/or code organization.

There is a Repo Organization included at the end of their proposal. 

- (Optional) Any further comments or feedback?

A better understanding of the data can result in finding out the best model for their project.

**Comment by eshaanmathakari** [comment]
Hi, thank you for your review! We have made the changes as per your feedback.
