### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by kmanasil** [INFO-523-Exercises/project-final-Feature-Finders-Club#73]
The following is the peer review of the project code by [name of team completing peer review]. The team members that participated in this review are 

- [Kristi Manasil] - @[kmanasil]
- [Dong Chen] - @[dongchen18]
- [Utkarsha Patil] - @utkarshapatil01
- [Anajani Sowmya Bollapragada] - @[asbollapragada]
- [Rohit Hemaraja] - @Rohit-Hemaraja
- ...
---

#### 1. Purpose of Code
- [ ] Clearly defined and understood
- [ ] All code in in the code.qmd file from what we can tell and it would be slightly easier to understand if it was broken down into multiple qmds. The layout of the code qmd is good as each section is clearly defined
- [ ] Ambiguous or unclear
- [ ] How was the timeframe decided. And why was apple selected. It could a more clear description of news source would be nice to see (what organization is the news coming from.

---

#### 2. Code Quality

- [ ] Code is clean, readable, and well-organized
- [ ] Yes
- [ ] 
- [ ] Adequate comments explaining complex or tricky code sections
- [ ] Add more comments explaining api calls
- [ ] 
- [ ] Variables, methods, and classes have meaningful names
- [ ] yes
- [ ] 
- [ ] Consistent code style (indentation, naming conventions, etc.)
- [ ] yes

---

#### 3. Documentation

- [ ] Code documentation (e.g., comments) is sufficient
- [ ] add more to the final project notebook
- [ ] Readme or other documentation updated if necessary
- [ ] this is not done yet

---

#### 4. Best Practices

- [ ] No hardcoded values; constants used appropriately
- [ ] Yes
- [ ] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [ ] Yes
- [ ] Code avoids repetition and promotes reusability
- [ ] Yes

---

#### 5. Additional Comments

- Please provide feedback, areas of improvement, or other observations.
- Question about multiple languages being used in final project notebook. Some of the code should be in the main repo and organized accordingly. The project seems to be lacking in visualizations and explanations of the analysis.

---

#### 6. Recommendation

- [ ] Approved - ready to be merged
- [ X] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by eshaanmathakari** [comment]
Thank you for your review, we will make changes accordingly.
