### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by ajinkyapdeshmukh10** [INFO-523-Exercises/project-final-Feature-Finders-Club#77]
The following is the peer review of the project code by [name of team completing peer review]. The team members who participated in this review are 

- Riyanshi Bohra - @riyanshibohra
- Kendall Beaver - @kendallbeaver
- Udit Chaudhary - @uditChaudhary242
- DhanyaPriya Somasundaram - @SaiDhanyaa
- Ajinkya Deshmukh- @ajinkyapdeshmukh10
---

#### 1. Purpose of Code
- [X] Clearly defined and understood
- [ ] Ambiguous or unclear

---

#### 2. Code Quality

- [X] Code is clean, readable, and well-organized
- [X] Adequate comments explaining complex or tricky code sections
- [X] Variables, methods, and classes have meaningful names
- [X] Consistent code style (indentation, naming conventions, etc.)

---

#### 3. Documentation

- [ ] Code documentation (e.g., comments) is sufficient
- [X] Readme or other documentation updated if necessary

---

#### 4. Best Practices

- [X] No hardcoded values; constants used appropriately
- [X] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [X] Code avoids repetition and promotes reusability

---

#### 5. Additional Comments

- Please provide feedback, areas of improvement, or other observations.

--- Put the code in the main branch, not supposed to put it in the _extra.
--- Make sure all the codes are completed and not left unacknowledged.

#### 6. Recommendation

- [ ] Approved - ready to be merged
- [X] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by eshaanmathakari** [comment]
Thank you for your review, we will make changes accordingly.
