### ISSUE TITLE
Presentation feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/project-final-Feature-Finders-Club#93]
Dear Feature Finders Club: Below is the score breakdown for your presentation. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Time management     | 2         |    0    |
| Professionalism | 2         |   2     |
| Teamwork | 3         |     3   |
| Slides | 3         |   2     |
| Creativity Critical Thought | 3 | 3|
| Content - Q1 | 6 | 5|
| Content - Q2 | 6 | 6 |
| Total    | 25        |    21    |

**Feedback**:
Time Management: The presentation was almost 20 minutes. This is way too long.
Slides: Some of the slides had a lot of information that would be better as visuals
Content: I didn't agree with the causal language of your interpretation on the correlation between sentiment and stock price. Just because the plot seems to have a piecewise relationship (meaning a relationship at times), doesn't mean there is an actual relationship. You would need to run something like a segmented regression to conclude that the relationship actually exists.

**Comment by LikithKumarDundigalla** [comment]
Hi Greg, the total would sum up to 21, but it shows 20. Please can you update it. 

Thanks for the feedback @Gchism94.

**Comment by Gchism94** [comment]
Thanks for catching this.
